sonar.projectKey=EliasL94_Toolbox-IT
sonar.organization=eliasl94
sonar.host.url=https://sonarcloud.io

# Chemins des sources
sonar.sources=app,lib,components
sonar.exclusions=node_modules/**, .next/**, out/**, public/**, **/*.test.tsx, **/*.spec.ts
sonar.sourceEncoding=UTF-8

# Analyse spécifique au TypeScript
sonar.typescript.tsconfigPath=tsconfig.json
sonar.javascript.lcov.reportPaths=coverage/lcov.info
